server:
  port: 0
spring:
  application:
    name: user-service
  # RebbitMq 설정 추가
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  # h2 설정 ( JPA 꼭 있어야한다...)
#  datasource:
#    url: jdbc:h2:mem:testdb    # config yml로 옮긴다.
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true # 외부접속 허용
      path: /h2-console
  # Jpa설정
  jpa:
    show-sql: true
    defer-datasource-initialization: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

greeting:
  message: Welcom to the E-commerce.

logging:
  level:
    com.example.userservice: DEBUG

# Acturator 기능처리를 위한 설정
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh # refresh: Config 정보를 refresh

#token:
#    expiration_time: 86400000
#    secret: user_token

