server:
  port: 8888
spring:
  application:
    name: config-service

  # RebbitMq 설정 추가
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

#  profiles:
#    active: native

  cloud:
    config:
      server:
        # native를 사용할 경우 git config는 무시된다.
        # 사용법 : http://localhost:8888/파일명/native 를 호출하면 읽어오는 것을 확인
#        native:
#          search-locations: file:///${user.home}/IdeaProjects/configFile/native-file-repo

        git:
          uri: https://github.com/HiddenEvent/msa-settings
#          private 래파지토리 경우
#          username:
#          password:
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
